### ISSUE TITLE
"argument mismatch error "

### ISSUE THREAD

**Issue by ztdepztdep** [lanl/MF-LBM#15]
`Create directories.
mkdir -p ./1.exec
mkdir -p ./1.obj
mpif90   -O3  -ffree-line-length-300 -J ./1.obj/    -c 0.src/Misc.F90 -o 1.obj/Misc.o
0.src/Misc.F90:113:21:

  113 |       call MPI_Bcast(walls_global, nxGlobal*nyGlobal*nzGlobal, MPI_INTEGER1, 0, MPI_COMM_VGRID, ierr)
      |                     1
......
  360 |     call MPI_Bcast(pore_sum,1,MPI_INTEGER,0,MPI_COMM_vgrid,ierr)
      |                   2  
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(1)/INTEGER(4)).
0.src/Misc.F90:121:29:

  121 |               call MPI_Bcast(walls_global(1, 1, k), (nxGlobal)*(nyGlobal)*out3, MPI_INTEGER1, 0, MPI_COMM_VGRID, ierr)
      |                             1
......
  360 |     call MPI_Bcast(pore_sum,1,MPI_INTEGER,0,MPI_COMM_vgrid,ierr)
      |                   2          
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(1)/INTEGER(4)).
make: *** [makefile:151: 1.obj/Misc.o] Error 1
`

**Comment by ychen-hpc** [comment]
[for gcc10+, enable the following temporary fix in makefile: 
MISC_FLAGS += -fallow-argument-mismatch   ](https://github.com/lanl/MF-LBM/blob/11be324a97fe6331b2271102da370460715355e8/singlephase_3D/makefile#L69)
